apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master-${STAGE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: redis
        role: master
        stage: ${STAGE}
    spec:
      containers:
        - name: redis-master
          image: ${IMAGE_NAME}
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
          ports:
            - containerPort: 6379
          env:
            - name: MASTER
              value: "true"
            - name: STAGE
              value: ${STAGE}
      volumes:
        - name: data
          emptyDir: {}
