apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel-${STAGE}
  namespace: ${NAMESPACE}
spec:
  serviceName: "redis-sentinel-${STAGE}"
  replicas: 4
  template:
    metadata:
      labels:
        type: redis-sentinel
        stage: ${STAGE}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: type
                  operator: In
                  values:
                    - redis-sentinel
                - key: stage
                  operator: In
                  values:
                    - ${STAGE}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sentinel
        image: ${IMAGE_NAME}
        readinessProbe:
          exec:
            command: ['redis-cli', '-p', '26379', 'info', 'server']
        ports:
          - containerPort: 26379
        env:
          - name: REDIS_INSTANCE_TYPE
            value: sentinel
          - name: STAGE
            value: ${STAGE}
          - name: NAMESPACE
            value: ${NAMESPACE}
