apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-${STAGE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: redis
        role: sentinel
        stage: ${STAGE}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: role
                  operator: In
                  values:
                    - sentinel
                - key: stage
                  operator: In
                  values:
                    - ${STAGE}
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis-sentinel
          image: ${IMAGE_NAME}
          ports:
            - containerPort: 26379
          env:
            - name: SENTINEL
              value: "true"
            - name: STAGE
              value: ${STAGE}
