apiVersion: v1
kind: Service
metadata:
  name: redis-${STAGE}
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    type: redis
    stage: ${STAGE}
