apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-${STAGE}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: redis
        role: slave
        stage: ${STAGE}
    spec:
      containers:
        - name: redis
          image: ${IMAGE_NAME}
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
          ports:
            - containerPort: 6379
          env:
            - name: STAGE
              value: ${STAGE}
      volumes:
        - name: data
          emptyDir: {}
