apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-slave-${STAGE}
  namespace: ${NAMESPACE}
spec:
  serviceName: "redis-slave-${STAGE}"
  replicas: 2
  template:
    metadata:
      labels:
        type: redis-slave
        stage: ${STAGE}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: type
                  operator: In
                  values:
                    - redis-slave
                - key: stage
                  operator: In
                  values:
                    - ${STAGE}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-slave
        image: ${IMAGE_NAME}
        readinessProbe:
          exec:
            command: ['redis-cli', '-p', '6379', 'info', 'server']
        ports:
          - containerPort: 6379
        env:
          - name: STAGE
            value: ${STAGE}
          - name: NAMESPACE
            value: ${NAMESPACE}
