apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-${STAGE}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: redis
        role: standalone
        stage: ${STAGE}
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
